package Day4;

public class Exception {
	
		/*try {
			int num =10/0;
		}catch (ArithmeticException e) {
			System.out.println("Cannot divide by zero:"+e.getMessage());
		}finally {
			System.out.println("Execution completed.");
		}
		
	}
}*/
		//throw exception
	/*static void checkAge(int age) {
		if (age < 18) {
			throw new IllegalArgumentException
			("Age must be 18 or older.");
	}
		System.out.println("Access granted");
		}
	public static void main(String[] args) {
		try {
			checkAge(16);
				} catch (IllegalArgumentException e) {
					System.out.println("Caught Exception:"+ e.getMessage());
					}
	}
	}*/
	
// 
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	